services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ../server:/workspace:cached
    command: sleep infinity
    networks:
      - database
  database:
    image: postgres:17.4-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - database

volumes:
  postgres-data:

networks:
  database:
